# Generated by Django 5.2.6 on 2025-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(help_text='Car model and brand', max_length=255)),
                ('license_start', models.DateField(help_text='License start date')),
                ('license_end', models.DateField(help_text='License expiration date')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['id'],
            },
        ),
    ]
