# Generated by Django 5.1.2 on 2025-09-25 18:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('day_name', models.CharField(max_length=16)),
                ('driver_name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('oil', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fines', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maintenance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spare_parts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tires', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('washing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week_start', models.DateField(help_text='Saturday date for the week this entry belongs to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='cars.car')),
            ],
            options={
                'ordering': ['-inspection_date', 'car_id'],
                'indexes': [models.Index(fields=['car', 'week_start'], name='cars_dailye_car_id_84a47d_idx'), models.Index(fields=['inspection_date'], name='cars_dailye_inspect_b52849_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Saturday date (week start)')),
                ('week_end', models.DateField(help_text='Friday date (week end)')),
                ('odometer_start', models.PositiveIntegerField()),
                ('odometer_end', models.PositiveIntegerField()),
                ('driver_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('custody', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='cars.car')),
            ],
            options={
                'ordering': ['-week_start', 'car_id'],
                'indexes': [models.Index(fields=['car', 'week_start'], name='cars_weekly_car_id_d4b348_idx')],
                'unique_together': {('car', 'week_start')},
            },
        ),
    ]
