# Generated by Django 5.1.2 on 2025-10-02 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_dailyentry_weeklysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='without',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional unspecified expense to include in totals', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
