# Generated by Django 5.1.2 on 2025-10-02 11:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_dailyentry_without_weeklysummary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='default_freight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alternative freight bucket that is not added to normal freight totals', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='default_net_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
