# Generated by Django 5.1.2 on 2025-10-06 16:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_dailyentry_default_freight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('air_filter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('oil_filter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gas_filter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('oil_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spare_part_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entries', to='cars.car')),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['car', 'date'], name='cars_mainte_car_id_e1722a_idx')],
            },
        ),
    ]
