# Generated by Django 5.1.2 on 2025-10-30 14:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_maintenanceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysummary',
            name='net_car',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net for car: (freight + default_freight + custody) - (net_expenses + perished + driver_salary)', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='net_driver',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net for driver: (freight + custody) - net_expenses', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='perished',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Perished goods value entered once per week', max_digits=12),
        ),
    ]
