# Generated by Django 5.1.2 on 2026-02-16 01:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_weeklysummary_net_car_weeklysummary_net_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='driver_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expenses related to the driver', max_digits=12),
        ),
    ]
